version: '3.8'
services:
  dir-server:
    build:
      context: .
      dockerfile: Dockerfile.dir-server
    container_name: dir-server
    networks:
      dmz_net:
        ipv4_address: 10.10.20.10
  fw-perimeter:
  client-lan:
  admin-pc:


networks:
  lan_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  
  dmz_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.10.20.0/24

  
  
